INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "디즈니 베이비 신세계 경기 팝업"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "디즈니 베이비 신세계 경기 팝업"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "디즈니 베이비 신세계 경기 팝업"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "LG전자 팝업스토어 우와한 Life's Good 연구소"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "LG전자 팝업스토어 우와한 Life's Good 연구소"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "LG전자 팝업스토어 우와한 Life's Good 연구소"), (SELECT category_id FROM category WHERE name = "콘텐츠"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "홈레코딩 A to Z 꿈꾸던 집업실 팝업스토어"), (SELECT category_id FROM category WHERE name = "연예"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "홈레코딩 A to Z 꿈꾸던 집업실 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "홈레코딩 A to Z 꿈꾸던 집업실 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "차앤박 X 뵈르뵈르 <차앤박 빈티지 쿨링 랩 팝업>"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "차앤박 X 뵈르뵈르 <차앤박 빈티지 쿨링 랩 팝업>"), (SELECT category_id FROM category WHERE name = "연예"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "차앤박 X 뵈르뵈르 <차앤박 빈티지 쿨링 랩 팝업>"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "오프닝프로젝트 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "오프닝프로젝트 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "오프닝프로젝트 팝업스토어"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "취 X 무신사 뷰티 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "취 X 무신사 뷰티 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "취 X 무신사 뷰티 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "텐바이텐 팝업스토어 in 현대백화점 판교점"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "텐바이텐 팝업스토어 in 현대백화점 판교점"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "텐바이텐 팝업스토어 in 현대백화점 판교점"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "토리버치 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "토리버치 팝업스토어"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "토리버치 팝업스토어"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "2024 서울썸머비치 라춘도 쬬비치"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "2024 서울썸머비치 라춘도 쬬비치"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "2024 서울썸머비치 라춘도 쬬비치"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "베티붑 팝업스토어 with 얼킨"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "베티붑 팝업스토어 with 얼킨"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "베티붑 팝업스토어 with 얼킨"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "미니언즈x하울팟 펫 팝업스토어 분당점"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "미니언즈x하울팟 펫 팝업스토어 분당점"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "미니언즈x하울팟 펫 팝업스토어 분당점"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "미니언즈x하울팟 펫 팝업스토어 한남점"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "미니언즈x하울팟 펫 팝업스토어 한남점"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "미니언즈x하울팟 펫 팝업스토어 한남점"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "오브젝트 서교점 : 나이브가든 Assemble! 팝업스토어"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "오브젝트 서교점 : 나이브가든 Assemble! 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "오브젝트 서교점 : 나이브가든 Assemble! 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "오둥이의 아르바이트 수원 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "오둥이의 아르바이트 수원 팝업스토어"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "오둥이의 아르바이트 수원 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "최고심 홍대플래그십 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "최고심 홍대플래그십 팝업스토어"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "최고심 홍대플래그십 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "갤럭시 스튜디오 서핑 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "갤럭시 스튜디오 서핑 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "갤럭시 스튜디오 서핑 팝업스토어"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "베이글리스트 X 라크루뜨 서울 팝업스토어"), (SELECT category_id FROM category WHERE name = "음식/음료"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "베이글리스트 X 라크루뜨 서울 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "베이글리스트 X 라크루뜨 서울 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "롯데월드 X 명탐정 코난 팝업 MAGIC CITY"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "롯데월드 X 명탐정 코난 팝업 MAGIC CITY"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "롯데월드 X 명탐정 코난 팝업 MAGIC CITY"), (SELECT category_id FROM category WHERE name = "연예"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "배틀그라운드 팝업스토어 PUBG 성수"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "배틀그라운드 팝업스토어 PUBG 성수"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "배틀그라운드 팝업스토어 PUBG 성수"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "휠라 언더웨어 X 러브이즈트루 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "휠라 언더웨어 X 러브이즈트루 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "휠라 언더웨어 X 러브이즈트루 팝업스토어"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "지구랜드 유닛 팝업 '지구스테이션'"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "지구랜드 유닛 팝업 '지구스테이션'"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "지구랜드 유닛 팝업 '지구스테이션'"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "젠틀몬스터 X 뮈글러 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "젠틀몬스터 X 뮈글러 팝업스토어"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "젠틀몬스터 X 뮈글러 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "강릉 여름 산책 팝업스토어"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "강릉 여름 산책 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "강릉 여름 산책 팝업스토어"), (SELECT category_id FROM category WHERE name = "연예"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "CU 팀코리아 골드 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "CU 팀코리아 골드 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "CU 팀코리아 골드 팝업스토어"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "폴더 X 우주먼지 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "폴더 X 우주먼지 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "폴더 X 우주먼지 팝업스토어"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "리드볼트 롯데월드몰 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "리드볼트 롯데월드몰 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "리드볼트 롯데월드몰 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "팝업상륙작전 더현대 팝업스토어"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "팝업상륙작전 더현대 팝업스토어"), (SELECT category_id FROM category WHERE name = "음식/음료"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "팝업상륙작전 더현대 팝업스토어"), (SELECT category_id FROM category WHERE name = "연예"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "모여봐요 동물의 숲 × 코엑스 아쿠아리움"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "모여봐요 동물의 숲 × 코엑스 아쿠아리움"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "모여봐요 동물의 숲 × 코엑스 아쿠아리움"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "레고트 TUMGGU 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "레고트 TUMGGU 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "레고트 TUMGGU 팝업스토어"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "쉬즈베이글 X 브레드이발소 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "쉬즈베이글 X 브레드이발소 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "쉬즈베이글 X 브레드이발소 팝업스토어"), (SELECT category_id FROM category WHERE name = "음식/음료"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "가루쌀 팝업스토어"), (SELECT category_id FROM category WHERE name = "음식/음료"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "가루쌀 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "가루쌀 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "아디다스 FC BAYERN 팝업 스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "아디다스 FC BAYERN 팝업 스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "아디다스 FC BAYERN 팝업 스토어"), (SELECT category_id FROM category WHERE name = "콘텐츠"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "명탐정 코난: 100만 달러의 펜타그램 BIAF 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "명탐정 코난: 100만 달러의 펜타그램 BIAF 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "명탐정 코난: 100만 달러의 펜타그램 BIAF 팝업스토어"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "미니언즈 팝업스토어 in판교 현대백화점"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "미니언즈 팝업스토어 in판교 현대백화점"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "미니언즈 팝업스토어 in판교 현대백화점"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "갤럭시 스튜디오 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "갤럭시 스튜디오 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "갤럭시 스튜디오 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "24년 짱구는 못말려 전주 팝업스토어 <짱구는 여행중!>"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "24년 짱구는 못말려 전주 팝업스토어 <짱구는 여행중!>"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "24년 짱구는 못말려 전주 팝업스토어 <짱구는 여행중!>"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "LG 홈브루하우스 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "LG 홈브루하우스 팝업스토어"), (SELECT category_id FROM category WHERE name = "가전/디지털"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "LG 홈브루하우스 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "마리끌레르 성수 팝업스토어 MARINERS CLUB"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "마리끌레르 성수 팝업스토어 MARINERS CLUB"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "마리끌레르 성수 팝업스토어 MARINERS CLUB"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "카누 하남 팝업스토어 <그랜드 카누 호텔>"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "카누 하남 팝업스토어 <그랜드 카누 호텔>"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "카누 하남 팝업스토어 <그랜드 카누 호텔>"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "더티스(thetis) 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "더티스(thetis) 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "더티스(thetis) 팝업스토어"), (SELECT category_id FROM category WHERE name = "연예"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "휴유 팝업스토어"), (SELECT category_id FROM category WHERE name = "음식/음료"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "휴유 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "휴유 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "주니토니 팝업스토어 in 판교"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "주니토니 팝업스토어 in 판교"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "주니토니 팝업스토어 in 판교"), (SELECT category_id FROM category WHERE name = "음식/음료"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "FC 세븐일레븐 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "FC 세븐일레븐 팝업스토어"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "FC 세븐일레븐 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "카드캡터사쿠라전 (展) | 마법의 걸린 미술관 대구"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "카드캡터사쿠라전 (展) | 마법의 걸린 미술관 대구"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "카드캡터사쿠라전 (展) | 마법의 걸린 미술관 대구"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "데드풀과 울버린 팝업스토어 <DEADPOOL&WOLVERINE>"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "데드풀과 울버린 팝업스토어 <DEADPOOL&WOLVERINE>"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "데드풀과 울버린 팝업스토어 <DEADPOOL&WOLVERINE>"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "라로제 X 아난티 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "라로제 X 아난티 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "라로제 X 아난티 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "T팩토리 전시 <Horok! 술림픽>"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "T팩토리 전시 <Horok! 술림픽>"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "T팩토리 전시 <Horok! 술림픽>"), (SELECT category_id FROM category WHERE name = "연예"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "두두스토리 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "두두스토리 팝업스토어"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "두두스토리 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "무브먼트 랩 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "무브먼트 랩 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "무브먼트 랩 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "레이지스튜디오 팝업스토어 <마이 타투 다이어리>"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "레이지스튜디오 팝업스토어 <마이 타투 다이어리>"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "레이지스튜디오 팝업스토어 <마이 타투 다이어리>"), (SELECT category_id FROM category WHERE name = "연예"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "세모 X 상상마당 팝업스토어 <Semo's Summer Holiday>"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "세모 X 상상마당 팝업스토어 <Semo's Summer Holiday>"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "세모 X 상상마당 팝업스토어 <Semo's Summer Holiday>"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "스누피가든 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "스누피가든 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "스누피가든 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "망그러진곰 비밀의 다락방 팝업스토어"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "망그러진곰 비밀의 다락방 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "망그러진곰 비밀의 다락방 팝업스토어"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "세탁특공대 팝업스토어 WASHER"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "세탁특공대 팝업스토어 WASHER"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "세탁특공대 팝업스토어 WASHER"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "페이퍼메세지 X 프렐류드 팝업스토어 <안녕하세요 대전>"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "페이퍼메세지 X 프렐류드 팝업스토어 <안녕하세요 대전>"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "페이퍼메세지 X 프렐류드 팝업스토어 <안녕하세요 대전>"), (SELECT category_id FROM category WHERE name = "콘텐츠"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "골든볼 팝업스토어"), (SELECT category_id FROM category WHERE name = "음식/음료"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "골든볼 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "골든볼 팝업스토어"), (SELECT category_id FROM category WHERE name = "가전/디지털"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "전시 <reSOUND: 울림, 그 너머>"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "전시 <reSOUND: 울림, 그 너머>"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "전시 <reSOUND: 울림, 그 너머>"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "연재 30주년 기념 명탐정코난전"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "연재 30주년 기념 명탐정코난전"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "연재 30주년 기념 명탐정코난전"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "K-museums 공동기획전 <노릇노릇 부산>"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "K-museums 공동기획전 <노릇노릇 부산>"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "K-museums 공동기획전 <노릇노릇 부산>"), (SELECT category_id FROM category WHERE name = "가전/디지털"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "개울 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "개울 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "개울 팝업스토어"), (SELECT category_id FROM category WHERE name = "연예"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "락피쉬 부산 전포 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "락피쉬 부산 전포 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "락피쉬 부산 전포 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "이토 준지 호러하우스"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "이토 준지 호러하우스"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "이토 준지 호러하우스"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "국립중앙박물관 특별전 <우리가 인디언으로 알던 사람들>"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "국립중앙박물관 특별전 <우리가 인디언으로 알던 사람들>"), (SELECT category_id FROM category WHERE name = "가전/디지털"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "국립중앙박물관 특별전 <우리가 인디언으로 알던 사람들>"), (SELECT category_id FROM category WHERE name = "콘텐츠"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "국립중앙박물관 특별전 <三國三色-동아시아의 칠기>"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "국립중앙박물관 특별전 <三國三色-동아시아의 칠기>"), (SELECT category_id FROM category WHERE name = "가전/디지털"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "국립중앙박물관 특별전 <三國三色-동아시아의 칠기>"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "2024 주술회전 팝업스토어 in 더현대 대구"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "2024 주술회전 팝업스토어 in 더현대 대구"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "2024 주술회전 팝업스토어 in 더현대 대구"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "소소히히 팝업스토어 in 서면"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "소소히히 팝업스토어 in 서면"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "소소히히 팝업스토어 in 서면"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "소소히히 팝업스토어 in 성수"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "소소히히 팝업스토어 in 성수"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "소소히히 팝업스토어 in 성수"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "소소히히 팝업스토어 in 홍대"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "소소히히 팝업스토어 in 홍대"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "소소히히 팝업스토어 in 홍대"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "나우인명동 X 스누피 마켓 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "나우인명동 X 스누피 마켓 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "나우인명동 X 스누피 마켓 팝업스토어"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "팝퍼블 X 원피스 콜라보 카페"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "팝퍼블 X 원피스 콜라보 카페"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "팝퍼블 X 원피스 콜라보 카페"), (SELECT category_id FROM category WHERE name = "음식/음료"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "샵사이다 롯데월드몰 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "샵사이다 롯데월드몰 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "샵사이다 롯데월드몰 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "키링집 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "키링집 팝업스토어"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "키링집 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "MMCA 기증작품전: 1960-70년대 구상회화"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "MMCA 기증작품전: 1960-70년대 구상회화"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "MMCA 기증작품전: 1960-70년대 구상회화"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "하비에르 카예하 특별전 <이곳에 예술은 없다>"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "하비에르 카예하 특별전 <이곳에 예술은 없다>"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "하비에르 카예하 특별전 <이곳에 예술은 없다>"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "오크베리 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "오크베리 팝업스토어"), (SELECT category_id FROM category WHERE name = "음식/음료"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "오크베리 팝업스토어"), (SELECT category_id FROM category WHERE name = "콘텐츠"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "원피스 대해적시대展"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "원피스 대해적시대展"), (SELECT category_id FROM category WHERE name = "콘텐츠"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "원피스 대해적시대展"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "취 성수 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "취 성수 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "취 성수 팝업스토어"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "국립한글박물관 기획특별전 <사투리는 못 참지!>"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "국립한글박물관 기획특별전 <사투리는 못 참지!>"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "국립한글박물관 기획특별전 <사투리는 못 참지!>"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "블레스문 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "블레스문 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "블레스문 팝업스토어"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "담곰이 카페"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "담곰이 카페"), (SELECT category_id FROM category WHERE name = "음식/음료"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "담곰이 카페"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "만화로 만나는 힙합"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "만화로 만나는 힙합"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "만화로 만나는 힙합"), (SELECT category_id FROM category WHERE name = "콘텐츠"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "요물, 우리를 홀린 고양이"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "요물, 우리를 홀린 고양이"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "요물, 우리를 홀린 고양이"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "두근두근 도라에몽전 in 부산"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "두근두근 도라에몽전 in 부산"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "두근두근 도라에몽전 in 부산"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "플레이모빌 맨션 : 6개의 방으로 놀러와"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "플레이모빌 맨션 : 6개의 방으로 놀러와"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "플레이모빌 맨션 : 6개의 방으로 놀러와"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "장인성의 말랑한 오피스"), (SELECT category_id FROM category WHERE name = "콘텐츠"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "장인성의 말랑한 오피스"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "장인성의 말랑한 오피스"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "헬로키티 50주년 특별전 : 산리오 캐릭터즈와의 여행"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "헬로키티 50주년 특별전 : 산리오 캐릭터즈와의 여행"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "헬로키티 50주년 특별전 : 산리오 캐릭터즈와의 여행"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "<하우스오브 미나리마 서울> 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "<하우스오브 미나리마 서울> 팝업스토어"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "<하우스오브 미나리마 서울> 팝업스토어"), (SELECT category_id FROM category WHERE name = "콘텐츠"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "마루콜렉트 팝업스토어 ‘FEEL SO GOODS: 굿즈에 진심인 스타트업들’"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "마루콜렉트 팝업스토어 ‘FEEL SO GOODS: 굿즈에 진심인 스타트업들’"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "마루콜렉트 팝업스토어 ‘FEEL SO GOODS: 굿즈에 진심인 스타트업들’"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "승리의 여신: 니케 2024 여름 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "승리의 여신: 니케 2024 여름 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "승리의 여신: 니케 2024 여름 팝업스토어"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "갤럭시 스튜디오 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "갤럭시 스튜디오 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "갤럭시 스튜디오 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "하이, 브리지톡 팝업 스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "하이, 브리지톡 팝업 스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "하이, 브리지톡 팝업 스토어"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "전시 <The Moonwalkers 더 문워커스 : 톰 행크스와 함께하는 여정>"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "전시 <The Moonwalkers 더 문워커스 : 톰 행크스와 함께하는 여정>"), (SELECT category_id FROM category WHERE name = "연예"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "전시 <The Moonwalkers 더 문워커스 : 톰 행크스와 함께하는 여정>"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "텐바이텐 팝업스토어 in 현대백화점 판교점"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "텐바이텐 팝업스토어 in 현대백화점 판교점"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "텐바이텐 팝업스토어 in 현대백화점 판교점"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "딥티크 NEW 헤도니스틱 썸머 X 성수 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "딥티크 NEW 헤도니스틱 썸머 X 성수 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "딥티크 NEW 헤도니스틱 썸머 X 성수 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "오밀조밀 과일가게 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "오밀조밀 과일가게 팝업스토어"), (SELECT category_id FROM category WHERE name = "연예"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "오밀조밀 과일가게 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "온브릭스 팝업스토어 in 성수"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "온브릭스 팝업스토어 in 성수"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "온브릭스 팝업스토어 in 성수"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "악역의 엔딩은 죽음뿐 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "악역의 엔딩은 죽음뿐 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "악역의 엔딩은 죽음뿐 팝업스토어"), (SELECT category_id FROM category WHERE name = "음식/음료"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "하츠네 미쿠 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "하츠네 미쿠 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "하츠네 미쿠 팝업스토어"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "에스티로더 My Shade, My Story Café 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "에스티로더 My Shade, My Story Café 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "에스티로더 My Shade, My Story Café 팝업스토어"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "쿠첸 팝업스토어 미토피아 페스티밥 in 하남"), (SELECT category_id FROM category WHERE name = "음식/음료"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "쿠첸 팝업스토어 미토피아 페스티밥 in 하남"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "쿠첸 팝업스토어 미토피아 페스티밥 in 하남"), (SELECT category_id FROM category WHERE name = "연예"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "청소광 브라이언 팝업스토어"), (SELECT category_id FROM category WHERE name = "리빙/금융"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "청소광 브라이언 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "청소광 브라이언 팝업스토어"), (SELECT category_id FROM category WHERE name = "가전/디지털"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "포플리의 조이 가든 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "포플리의 조이 가든 팝업스토어"), (SELECT category_id FROM category WHERE name = "취미/여가"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "포플리의 조이 가든 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "외모지상주의 10주년 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "외모지상주의 10주년 팝업스토어"), (SELECT category_id FROM category WHERE name = "캐릭터"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "외모지상주의 10주년 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "쎄시 시드르 목동 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "쎄시 시드르 목동 팝업스토어"), (SELECT category_id FROM category WHERE name = "음식/음료"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "쎄시 시드르 목동 팝업스토어"), (SELECT category_id FROM category WHERE name = "연예"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "로미네 집들이 팝업스토어"), (SELECT category_id FROM category WHERE name = "게임"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "로미네 집들이 팝업스토어"), (SELECT category_id FROM category WHERE name = "패션"));
INSERT INTO popup_category (popup_id, category_id) VALUES ((SELECT popup_id FROM popup WHERE name = "로미네 집들이 팝업스토어"), (SELECT category_id FROM category WHERE name = "뷰티"));
